#!/usr/bin/with-contenv bash

CDC="\e[0;36m" # cyan
CN="\e[0m"     # none

unset is_ok

[[ -z $PROVIDER ]] && PROVIDER="cryptostorm"

[[ -n $CONFIG ]] && is_ok=1
[[ -z $is_ok ]] && {
  [[ $PROVIDER == "cryptostorm" && -n ADDRESS && -n $SERVER && -n $PRIVATE_KEY && -n $PSK ]] && is_ok=1
  [[ $PROVIDER == "mullvad" && -n ADDRESS && -n $SERVER && -n $PRIVATE_KEY ]] && is_ok=1
}

[[ -z $is_ok ]] && {
  if [[ $PROVIDER == "cryptostorm" ]]; then
    echo -e "\
Either set CONFIG= or set ADDRESS=,PSK=,PRIVATE_KEY= and SERVER=\n\
--> Try \`${CDC}docker run --rm --env TOKEN=XXX --entrypoint /getkey.sh hackerschoice/cryptostorm${CN}\`"
  elif [[ $PROVIDER == "mullvad" ]]; then  
    echo -e "\
Either set CONFIG= or set ADDRESS=,PRIVATE_KEY= and SERVER=\n\
--> Get this information from https://mullvad.net/en/account/#/wireguard-config"
  else
    echo -e "Either set CONFIG= or set ADDRESS=,PRIVATE_KEY= and SERVER="
  fi

  sleep infinity
}

ip link del dev test 2>/dev/null
if ip link add dev test type wireguard; then
  ip link del dev test
else
  echo "[$(date -Iseconds)] The wireguard module is not active, try \`docker run --rm --cap-add=NET_ADMIN --cap-add=SYS_MODULE -v /lib/modules:/lib/modules\` to install it or follow the proper instructions from https://www.wireguard.com/install/ to manually install it."
  sleep infinity
fi

if ! iptables -L > /dev/null 2>&1; then
  echo "[$(date -Iseconds)] iptables is not functional. Ensure your container config adds --cap-add=NET_ADMIN" 
  sleep infinity
fi

